// Los nombres de canal IPC, en un solo lugar.
//
// Estaban duplicados literales entre src/main/ipc/index.ts y
// src/preload/index.ts, y ya habian divergido: al preload le faltaba
// 'config:obtener-impresora'. Un canal que existe de un lado y no del otro
// no falla al compilar --falla en produccion, cuando alguien lo invoca.
//
// El registro de handlers (main) y el puente contextBridge (preload) leen
// de aca. Si agregas un canal, va tambien el tipo en shared/types/api.ts.
export const CANALES = {
  productosObtener: 'productos:obtener',
  productosBuscar: 'productos:buscar',
  ventasRegistrar: 'ventas:registrar',
  ticketImprimir: 'ticket:imprimir',
  ticketNotaCredito: 'ticket:nota-credito',
  ticketArqueoZ: 'ticket:arqueo-z',
  ventasListar: 'ventas:listar',
  ventasDetalle: 'ventas:detalle',
  ventasAnular: 'ventas:anular',
  cajaAbrir: 'caja:abrir',
  cajaCerrar: 'caja:cerrar',
  cajaArqueoAbierto: 'caja:arqueo-abierto',
  cajaListarArqueos: 'caja:listar-arqueos',
  cajaRegistrarMovimiento: 'caja:registrar-movimiento',
  cajaListarMovimientos: 'caja:listar-movimientos',
  cuentasListar: 'cuentas:listar',
  cuentasCrear: 'cuentas:crear',
  cuentasActualizarEstado: 'cuentas:actualizar-estado',
  informesGanancias: 'informes:ganancias',
  informesGananciaTotal: 'informes:ganancia-total',
  informesEnvases: 'informes:envases',
  informesTopProductos: 'informes:top-productos',
  informesVentasPorHora: 'informes:ventas-por-hora',
  informesGananciaTotalNeta: 'informes:ganancia-total-neta',
  usuariosAutenticar: 'usuarios:autenticar',
  usuariosCerrarSesion: 'usuarios:cerrar-sesion',
  stockCritico: 'stock:critico',
  archivoGuardarCsv: 'archivo:guardar-csv',
  archivoGuardarExcel: 'archivo:guardar-excel',
  archivoExportarVentas: 'archivo:exportar-ventas',
  offlineVerificarConexion: 'offline:verificar-conexion',
  offlineEstado: 'offline:estado',
  offlineGuardarVenta: 'offline:guardar-venta',
  offlineVentasPendientes: 'offline:ventas-pendientes',
  offlineVentasFallidas: 'offline:ventas-fallidas',
  offlineOlvidarFallida: 'offline:olvidar-fallida',
  offlineSincronizar: 'offline:sincronizar',
  carritoGuardar: 'carrito:guardar',
  carritoRecuperar: 'carrito:recuperar',
  envasesListar: 'envases:listar',

  ventanaMinimizar: 'ventana:minimizar',
  ventanaMaximizar: 'ventana:maximizar',
  ventanaCerrar: 'ventana:cerrar',
  productosGenerarCodigo: 'productos:generar-codigo',
  productosImprimirEtiqueta: 'productos:imprimir-etiqueta',
  productosActualizarCodigo: 'productos:actualizar-codigo',
  productosListar: 'productos:listar',
  productosActualizar: 'productos:actualizar',
  productosCrear: 'productos:crear',
  productosEliminar: 'productos:eliminar',
  proveedoresListar: 'proveedores:listar',
  proveedoresCrear: 'proveedores:crear',
  comprasRegistrar: 'compras:registrar',
  comprasListar: 'compras:listar',
  clientesListar: 'clientes:listar',
  clientesCrear: 'clientes:crear',
  clientesActualizarLimite: 'clientes:actualizar-limite',
  clientesRegistrarCompraFiado: 'clientes:registrar-compra-fiado',
  clientesRegistrarAmortizacion: 'clientes:registrar-amortizacion',
  clientesEliminar: 'clientes:eliminar',
  actualizarCheck: 'actualizar:check',
  actualizarDescargar: 'actualizar:descargar',
  backupRealizar: 'backup:realizar',
  productosImportarExcel: 'productos:importar-excel',
  stockListaCompras: 'stock:lista-compras',
  stockImprimirLista: 'stock:imprimir-lista',
  categoriasListar: 'categorias:listar',
  categoriasCrear: 'categorias:crear',
  categoriasEliminar: 'categorias:eliminar',
  devolucionesCrear: 'devoluciones:crear',
  devolucionesListar: 'devoluciones:listar',
  configObtenerComercio: 'config:obtener-comercio',
  configGuardarComercio: 'config:guardar-comercio',
  configListarImpresoras: 'config:listar-impresoras',
  configGuardarImpresora: 'config:guardar-impresora',
  configTestImpresora: 'config:test-impresora',
  configEstadoConexion: 'config:estado-conexion',
  configGuardarConexion: 'config:guardar-conexion',
} as const;
