-- Cuentas a Pagar (proveedores) y Cuentas a Recibir (clientes)
create table if not exists "public"."cuentas_pagar" (
    "id_cuenta" bigint generated by default as identity primary key,
    "proveedor" text not null,
    "monto" numeric(12,0) not null,
    "saldo" numeric(12,0) not null,
    "concepto" text not null default '',
    "fecha_vencimiento" date,
    "fecha" timestamp with time zone default now() not null,
    "estado" text default 'pendiente' not null,
    constraint "cuentas_pagar_estado_check" check (estado in ('pendiente', 'pagada', 'cancelada'))
);

create table if not exists "public"."cuentas_recibir" (
    "id_cuenta" bigint generated by default as identity primary key,
    "cliente" text not null,
    "monto" numeric(12,0) not null,
    "saldo" numeric(12,0) not null,
    "concepto" text not null default '',
    "fecha_vencimiento" date,
    "fecha" timestamp with time zone default now() not null,
    "estado" text default 'pendiente' not null,
    constraint "cuentas_recibir_estado_check" check (estado in ('pendiente', 'cobrada', 'cancelada'))
);

comment on table "public"."cuentas_pagar" is 'Cuentas pendientes con proveedores';
comment on table "public"."cuentas_recibir" is 'Cuentas pendientes de clientes';

grant all on table public.cuentas_pagar to service_role;
grant usage on sequence public.cuentas_pagar_id_cuenta_seq to service_role;
grant all on table public.cuentas_recibir to service_role;
grant usage on sequence public.cuentas_recibir_id_cuenta_seq to service_role;
