-- Movimientos de caja: entrada/retirada de plata durante la jornada
create table if not exists "public"."movimientos_caja" (
    "id_movimiento" bigint generated by default as identity primary key,
    "id_arqueo" bigint references public.arqueos_caja(id_arqueo) on delete cascade,
    "tipo" text not null,
    "monto" numeric(12,0) not null,
    "concepto" text not null default '',
    "fecha" timestamp with time zone default now() not null,
    constraint "movimientos_caja_tipo_check" check (tipo in ('entrada', 'retirada'))
);

comment on table "public"."movimientos_caja" is 'Entradas y retiradas de plata manuales durante la jornada';

create or replace function public.registrar_movimiento_caja(
    p_id_arqueo bigint,
    p_tipo text,
    p_monto numeric(12,0),
    p_concepto text default ''
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
    v_row public.movimientos_caja;
begin
    if not exists (select 1 from public.arqueos_caja where id_arqueo = p_id_arqueo and estado = 'abierta') then
        raise exception 'No hay una caja abierta con ID %', p_id_arqueo using errcode = 'P0001';
    end if;
    insert into public.movimientos_caja (id_arqueo, tipo, monto, concepto)
    values (p_id_arqueo, p_tipo, p_monto, p_concepto)
    returning * into v_row;
    return row_to_json(v_row)::jsonb;
end;
$$;

create or replace function public.listar_movimientos_caja(p_id_arqueo bigint)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
    v_resultado jsonb;
begin
    select coalesce(jsonb_agg(row_to_json(m.*)::jsonb order by m.fecha), '[]'::jsonb) into v_resultado
    from public.movimientos_caja m
    where m.id_arqueo = p_id_arqueo;
    return v_resultado;
end;
$$;

revoke all on function public.registrar_movimiento_caja(bigint, text, numeric, text) from public;
revoke all on function public.listar_movimientos_caja(bigint) from public;
grant execute on function public.registrar_movimiento_caja(bigint, text, numeric, text) to service_role;
grant execute on function public.listar_movimientos_caja(bigint) to service_role;
grant all on table public.movimientos_caja to service_role;
grant usage on sequence public.movimientos_caja_id_movimiento_seq to service_role;
