-- Envases: seguimiento de envases retornables (botellas, cajones, etc.)
create table if not exists "public"."envases" (
    "id_envase" bigint generated by default as identity primary key,
    "nombre" text not null,
    "precio" numeric(12,0) not null default 0,
    "created_at" timestamp with time zone default now() not null
);

create table if not exists "public"."detalle_envases_venta" (
    "id_detalle" bigint generated by default as identity primary key,
    "id_venta" bigint references public.ventas(id_venta) on delete cascade,
    "id_envase" bigint references public.envases(id_envase),
    "cantidad" integer not null,
    "precio_unitario" numeric(12,0) not null
);

comment on table "public"."envases" is 'Catálogo de envases retornables';
comment on table "public"."detalle_envases_venta" is 'Envases registrados en cada venta';

grant all on table public.envases to service_role;
grant usage on sequence public.envases_id_envase_seq to service_role;
grant all on table public.detalle_envases_venta to service_role;
grant usage on sequence public.detalle_envases_venta_id_detalle_seq to service_role;
