-- Tabla de apertura/cierre de caja (arqueo)
create table if not exists "public"."arqueos_caja" (
    "id_arqueo" bigint generated by default as identity primary key,
    "fecha_apertura" timestamp with time zone default now() not null,
    "fondo_inicial" numeric(12,0) not null,
    "fecha_cierre" timestamp with time zone,
    "fondo_declarado" numeric(12,0),
    "total_efectivo" numeric(12,0) default 0,
    "total_tarjeta" numeric(12,0) default 0,
    "total_transferencia" numeric(12,0) default 0,
    "total_mixto" numeric(12,0) default 0,
    "total_ventas" numeric(12,0) default 0,
    "esperado_efectivo" numeric(12,0),
    "diferencia" numeric(12,0),
    "estado" text default 'abierta' not null,
    constraint "arqueos_caja_estado_check" check (estado in ('abierta', 'cerrada'))
);

comment on table "public"."arqueos_caja" is 'Registro de apertura y cierre de caja (arqueo diario)';
comment on column "public"."arqueos_caja"."fondo_inicial" is 'Efectivo con que arranca el cajero';
comment on column "public"."arqueos_caja"."esperado_efectivo" is 'fondo_inicial + total_efectivo';
comment on column "public"."arqueos_caja"."diferencia" is 'fondo_declarado - esperado_efectivo (+ sobrante, - faltante)';

-- RPC: abrir caja
create or replace function public.abrir_caja(p_fondo_inicial numeric(12,0))
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
    v_existente bigint;
    v_row public.arqueos_caja;
begin
    -- Verificar que no haya una caja abierta
    select id_arqueo into v_existente
      from public.arqueos_caja
     where estado = 'abierta'
     limit 1;
    if v_existente is not null then
        raise exception 'Ya hay una caja abierta (ID: %)', v_existente
            using errcode = 'P0001';
    end if;

    insert into public.arqueos_caja (fondo_inicial)
    values (p_fondo_inicial)
    returning * into v_row;

    return row_to_json(v_row)::jsonb;
end;
$$;

-- RPC: cerrar caja
create or replace function public.cerrar_caja(p_id_arqueo bigint, p_fondo_declarado numeric(12,0))
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
    v_arqueo public.arqueos_caja;
    v_efectivo numeric(12,0) := 0;
    v_tarjeta numeric(12,0) := 0;
    v_transferencia numeric(12,0) := 0;
    v_mixto numeric(12,0) := 0;
    v_total numeric(12,0) := 0;
    v_esperado numeric(12,0);
    v_diferencia numeric(12,0);
    v_row public.arqueos_caja;
begin
    select * into v_arqueo from public.arqueos_caja where id_arqueo = p_id_arqueo;
    if not found then
        raise exception 'Arqueo no encontrado: %', p_id_arqueo
            using errcode = 'P0001';
    end if;
    if v_arqueo.estado = 'cerrada' then
        raise exception 'La caja % ya está cerrada', p_id_arqueo
            using errcode = 'P0001';
    end if;

    -- Sumar ventas desde la apertura hasta ahora, filtradas por tipo_pago
    select
        coalesce(sum(case when tipo_pago = 'efectivo' then total_pagado else 0 end), 0),
        coalesce(sum(case when tipo_pago = 'tarjeta' then total_pagado else 0 end), 0),
        coalesce(sum(case when tipo_pago = 'transferencia' then total_pagado else 0 end), 0),
        coalesce(sum(case when tipo_pago = 'mixto' then total_pagado else 0 end), 0),
        coalesce(sum(total_pagado), 0)
    into v_efectivo, v_tarjeta, v_transferencia, v_mixto, v_total
    from public.ventas
    where fecha_hora >= v_arqueo.fecha_apertura
      and estado = 'activa';

    v_esperado := v_arqueo.fondo_inicial + v_efectivo;
    v_diferencia := p_fondo_declarado - v_esperado;

    update public.arqueos_caja set
        fecha_cierre = now(),
        fondo_declarado = p_fondo_declarado,
        total_efectivo = v_efectivo,
        total_tarjeta = v_tarjeta,
        total_transferencia = v_transferencia,
        total_mixto = v_mixto,
        total_ventas = v_total,
        esperado_efectivo = v_esperado,
        diferencia = v_diferencia,
        estado = 'cerrada'
    where id_arqueo = p_id_arqueo
    returning * into v_row;

    return row_to_json(v_row)::jsonb;
end;
$$;

-- RPC: obtener arqueo abierto (si existe)
create or replace function public.obtener_arqueo_abierto()
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
    v_row public.arqueos_caja;
begin
    select * into v_row
      from public.arqueos_caja
     where estado = 'abierta'
     limit 1;

    if v_row.id_arqueo is null then
        return null;
    end if;

    return row_to_json(v_row)::jsonb;
end;
$$;

-- Grants
revoke all on function public.abrir_caja(numeric) from public;
revoke all on function public.cerrar_caja(bigint, numeric) from public;
revoke all on function public.obtener_arqueo_abierto() from public;

grant execute on function public.abrir_caja(numeric) to service_role;
grant execute on function public.cerrar_caja(bigint, numeric) to service_role;
grant execute on function public.obtener_arqueo_abierto() to service_role;

grant all on table public.arqueos_caja to service_role;
grant usage on sequence public.arqueos_caja_id_arqueo_seq to service_role;
